### ISSUE TITLE
Use color_attributes instead of vertex_colors when exporting

### ISSUE THREAD

**Issue by PrismaticFlower** [PrismaticFlower/SWBF-msh-Blender-IO#11]
From [here](https://docs.blender.org/api/bpy.types.Mesh.html#bpy.types.Mesh.vertex_colors) 
>Legacy vertex color layers. Deprecated, use color attributes instead

**Comment by LeovanGit** [comment]
I tried to fix it here: https://github.com/PrismaticFlower/SWBF-msh-Blender-IO/pull/12
