### ISSUE TITLE
Deleting faces in blender breaks view in ZE

### ISSUE THREAD

**Issue by phantom567459** [PrismaticFlower/SWBF-msh-Blender-IO#3]
I have a model of a map that is used in Jedi Knight using another converter tool on Github.  Jedi Knight breaks the game into sectors using polygons with no material on them.
If I do the export to msh immediately, the model will load fine in ZE and will munge and show up ingame.

I select these faces by material and delete them.  If I export now, the model will not load into ZeroEditor, and cannot be imported into XSI due to an "n-gon" error. The model can be re-imported into Blender and exported again, but the issue persists. The models can be successfully munged and loaded ingame with no issue, except that I have to place them using text rather than ZE.

Doing the same process in XSI results in a model viewable in ZE and ingame.

Suggestions?

**Comment by WHSnyder** [comment]
Should be fixed by 7b9f5c9cfbb785ea0f364e57197a7a2f548548ef.  Included in the v1.2.0 release.  If it continues, do reopen the issue.
