### ISSUE TITLE
Smoothing groups from MSH not imported

### ISSUE THREAD

**Issue by SirYodaJedi** [PrismaticFlower/SWBF-msh-Blender-IO#4]
I am using pre-release version [v1.0.0rc](../releases/tag/1.0.0-rc).

When importing an MSH model into blender, the model is flat-shaded, and no smoothing groups are present.

For example, here is how `BF2_ModTools\assets\worlds\NAB\msh\nab2_prop_fountain.msh` appears immediately after import, with viewport shading set to solid (to emphasize the shading). As you can see, the meshes are flat-shaded.
![msh_smoothing_issue](https://user-images.githubusercontent.com/50331474/183730770-c648c058-77ef-420b-8c3f-1650445967b2.png)
Going into modeling view, you can see that none of the edges are marked as sharp.
![image](https://user-images.githubusercontent.com/50331474/183734212-b5a62e5d-a96b-45f7-9b30-40a3346d32f5.png)
I have also verified this to be the case with other models, such as the LA-AT. I do not know if this is a problem with the tool or an inherent limitation of the MSH format, but if it is a format issue, then the tool should at least import the meshes as smooth shaded by default, as that is how the models are displayed in-game.

**Comment by WHSnyder** [comment]
Supported by https://github.com/PrismaticFlower/SWBF-msh-Blender-IO/commit/5d86a88411f78bef59e4b573325153520afe6c8e and https://github.com/PrismaticFlower/SWBF-msh-Blender-IO/commit/13a92e46c670a76a866a89d481a3153e8f5371a3 

Will be included in official release.  Apologies for the delay!
